name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "upbox-api"
          heroku_email: "viniciusgcp@gmail.com"
          appdir: api-upbox/
          justlogin: true

      - name: Verify .netrc
        run: cat ~/.netrc
      
      - name: Add remote
        run: heroku git:remote -a upbox-api

      - name: Verify remote list
        run: git remote -v

      - name: Push to Heroku
        run: git push heroku `git subtree split --prefix=api-upbox/ HEAD`:master --force
