name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  api-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./api-upbox

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Add Heroku remote
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku
        run: git subtree push --prefix api-upbox/ heroku master
        working-directory: ./

